config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  devise_for :users

  resources :references
  resources :posts
  get 'pages/home'
  get 'actualites', to: 'pages#posts', as: :actualites
  get 'a_propos', to: 'pages#about', as: :about
  get 'inscription', to: 'pages#inscription', as: :inscription
  post 'inscription_create', to: 'pages#inscription_create', as: :inscription_create

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :content, :category, presence: true
  default_scope -> { order(updated_at: :desc) }
end

app/models/reference.rb
class Reference < ApplicationRecord
  validates :name, presence: true

  default_scope { order(:name) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise  :database_authenticatable,
          :rememberable
          # :registerable, :recoverable, 
          # :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  def home
    @posts = Post.first(3)
    @references = Reference.all
  end
  def posts
    @posts = Post.all
    unless params[:category].blank?
      @category = params[:category]
      @posts = @posts.where(category: @category)
    end
  end
  def about
  end
  def inscription
    @post_id = params[:post_id]
  end
  def inscription_create
    @post = Post.find(params[:post_id])
    @email = params[:email]
    
    respond_to do |format|
      DownloadMailer.with(post: @post, email: @email).download_request.deliver_now
      format.html { redirect_to root_path, notice: "Votre message a bien été pris envoyé. Vous recevrez les documents prochainement." }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[ show ]
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Le Post a bien été créé." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Le Post a bien été mis à jour." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Le Post a bien été supprimé." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :category, :document)
    end
end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController
  before_action :set_reference, only: %i[ show edit update destroy ]

  # GET /references or /references.json
  def index
    @references = Reference.all
  end

  # GET /references/1 or /references/1.json
  def show
  end

  # GET /references/new
  def new
    @reference = Reference.new
  end

  # GET /references/1/edit
  def edit
  end

  # POST /references or /references.json
  def create
    @reference = Reference.new(reference_params)

    respond_to do |format|
      if @reference.save
        format.html { redirect_to reference_url(@reference), notice: "Reference was successfully created." }
        format.json { render :show, status: :created, location: @reference }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /references/1 or /references/1.json
  def update
    respond_to do |format|
      if @reference.update(reference_params)
        format.html { redirect_to reference_url(@reference), notice: "Reference was successfully updated." }
        format.json { render :show, status: :ok, location: @reference }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /references/1 or /references/1.json
  def destroy
    @reference.destroy

    respond_to do |format|
      format.html { redirect_to references_url, notice: "Reference was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reference
      @reference = Reference.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reference_params
      params.require(:reference).permit(:name, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/references_helper.rb
module ReferencesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr" data-theme="admouvoir">
  <head>
    <title>adMouvoir - v0.11</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css2?family=Quicksand&display=swap" rel="stylesheet">
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

  </head>

  <body>
    <%= render partial: "partials/navbar" %>
    <%= render partial: "partials/notification" %>
    <main class="adm-bg-secondary min-h-screen">
      <%= yield %>
    </main>
    <%= render partial: "partials/footer" %>
  </body>
</html>

app/views/pages/_about.html.erb
<div id="a_propos" class="flex flex-col lg:px-32">
  <h2>Qui sommes-nous ?</h2>
  <div class="hero-content flex-col lg:flex-row items-start lg:pl-0">
    <div class="lg:mr-8">
      <p class="text-xl">
        Sylvie accompagne les dirigeants et leurs équipes qui veulent mettre en cohérence leurs actions et postures avec un projet stratégique mobilisateur qui fait sens. Elle intervient sur 3 axes majeurs :
        <br><br>
        <strong class="adm-text-primary">
          • Cultiver les talents managériaux,
          <br>
          • Apaiser les situations de tensions/de crise et
          <br>
          • Accompagner les personnes et les collectifs à se réinventer dans des moments de transitions.
        </strong>
        <br><br>
        Elle anime également des <strong class="adm-text-primary"><a href="/#conferences"><u>conférences suivies d’ateliers réflexifs</u></a></strong> sur les thèmes du management dans les organisations hybrides, (re)donner du sens au travail dans un monde d’incertitudes, écoute et leadership, devenir leader résilient, manager les paradoxes dans les organisations en transformation…
        <br><br>
        Son approche s’inscrit dans un cadre de référence <strong class="adm-text-primary">systémique</strong> (MBA de management général à HEC Paris), <strong class="adm-text-primary">humaniste</strong> (Master RH à IGS Paris) et <strong class="adm-text-primary">relationnel</strong> (Master of business coaching à International Mozaik).
        <br><br>
      </p>
    </div>
    <%= image_tag "plane.jpg", class: "max-w-full lg:max-w-sm rounded", loading: "lazy" %>
  </div>
  <p class="text-xl px-4 lg:px-0">
    Avant d’entreprendre à son compte, elle a été dirigeante salariée du cabinet conseil RH de la CCI de Paris Ile-de -France et a piloté les Relations humaines et sociales d’organisations publiques (CCI Paris, Centres d’observation et de recherche économique, ESCP, campus LÉA-CFI notamment).
  </p>
  <% if current_page?(root_path) %>
    <%= link_to "En savoir plus", about_path, class: "btn btn-outline btn-lg text-white mt-12 mx-4 lg:mx-0"%>
  <% end %>
</div>

app/views/pages/_advise.html.erb
<h2>
  Conseil & Formations
</h2>

app/views/pages/_calendar.html.erb
<div id="calendar" class="adm-bg-tertiary lg:px-32">
  <h2 class="text-black !mb-12">
    Besoin d'un rendez-vous ?
  </h2>
  <!-- Calendly inline widget begin -->
  <div class="calendly-inline-widget" data-url="https://calendly.com/p-edacquet?background_color=ffffff&text_color=155874&primary_color=2ad0ce" style="min-width:320px;height:700px;"></div>
  <script type="text/javascript" src="https://assets.calendly.com/assets/external/widget.js" async></script>
  <!-- Calendly inline widget end -->
</div>

app/views/pages/_coaching.html.erb
<h2>
  Coaching professionnel
</h2>

app/views/pages/_hero.html.erb
<div class="hero min-h-min w-screen" style="background-image: url(<%= asset_path('sky.jpg') %>)">
  <div class="hero-overlay w-fit"></div>
  <div class="hero-content text-center w-fit">
    <div class="py-20 lg:py-32">
      <h1 class="mb-5 text-6xl lg:text-8xl text-black">ad<strong class="font-black text-black">Mouvoir</strong></h1>
      <p class="mb-5 text-3xl lg:text-5xl adm-text-quaternary">Faire des organisations des lieux d’amélioration du monde, sources d’émancipation et d’épanouissement individuel et collectif</p>
    </div>
  </div>
</div>

app/views/pages/_partners.html.erb
<h2>
  Partenaires
</h2>

app/views/pages/_quote.html.erb
<div class="flex justify-center pb-12 adm-bg-primary px-4">
  <blockquote class="quote-card yellow-card pt-12">
    <p class="text-3xl text-black">
      « C'est impossible, dit la Fierté
      <br>
      C'est risqué, dit l'Expérience
      <br>
      C'est sans issue, dit la Raison
      <br>
      Essayons, mumure le Coeur. »
    </p>

    <br>
    <cite>
      William Arthur Ward
    </cite>
  </blockquote>
</div>

app/views/pages/_resources_news.html.erb
<div id="ressources" class="flex flex-col">
  <h2>
    Ressources et Actualités
  </h2>

  <div class="mb-12">
    <div class="flex flex-wrap gap-4 justify-center px-4">
      <%= render partial: "post_card", collection: @posts, as: :post %>
    </div>
  </div>
  <%= link_to "Voir toutes les ressources et actualités", actualites_path, class: "btn btn-outline btn-lg text-center text-white mx-4 lg:mx-auto" %>
</div>

app/views/pages/_références.html.erb
<h2 class="font-medium text-5xl text-center mb-12">
  Mes Références
</h2>

app/views/pages/about.html.erb
<%= render "about" %>

app/views/pages/home.html.erb
<!-- Render all partials for homepage -->
<%= render "hero" %>
<%= render "about" %>

<%
=begin%>
 <%= render "coaching" %>  
<%
=end%>
<%= render "conferences" %>
<%
=begin%>
 <%= render "advise" %>
<%= render "partners" %>  
<%
=end%>
<%= render "experiences" %>
<%= render "resources_news" %>
<%= render "references" %>
<%= render "calendar" %>
<%= render "contact" %>
<%= render "quote" %>

app/views/pages/inscription.html.erb
<div class="pt-10 lg:pt-28">
  <div class="p-10 lg:p-20 mx-auto max-w-fit border rounded-md border-slate-400">
    <p>
      Veuillez entrer votre email pour que nous puissions garder contact
    </p>

    <%= form_with(url: inscription_create_path, method: :post, data: { turbo_confirm: 'Vérifiez bien votre adresse e-mail, puis cliquez sur OK' }) do |form| %>

      <%= form.hidden_field :post_id, value: params[:post_id] %>

      <div class="my-5">
        <%= form.label :email, class: "text-2xl font-medium text-white" %>
        <%= form.text_field :email, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
      </div>

      <div class="inline">
        <%= form.submit "Valider", class: "btn btn-accent btn-outline" %>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/posts.html.erb
<div class="px-4 lg:px-12 pb-10 lg:pb-24">
  <h1 class="text-6xl text-center py-16">
    Ressources et Actualités
  </h1>
  <% if @category %>
    <h2 class="!text-3xl">
      Thème : <%= @category %>
      <%= link_to actualites_path do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block w-6 h-6 stroke-current"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path></svg>
      <% end %>
    </h2>
  <% end %>
  <div class="flex flex-wrap gap-4 justify-center px-4">
    <%= render partial: "post_card", collection: @posts, as: :post %>
  </div>
</div>

app/views/partials/_footer.html.erb
<footer class="footer footer-center p-4 lg:p-10 adm-bg-tertiary text-base-content">
  <div class="flex flex-col lg:flex-row gap-4 justify-center">
    <div class="flex gap-4 w-80 items-center justify-center lg:w-full">
      <a class="link link-hover text-black" href="/a_propos">Qui sommes-nous ?</a>
      <p class="text-black">•</p>
      <a class="link link-hover text-black">Conférences-Ateliers</a>
      <p class="hidden lg:block text-black">•</p>
    </div>
    <div class="flex gap-4 w-80 items-center justify-center lg:w-full">
      <a class="link link-hover text-black" href="#experiences">Galerie expériences</a>
      <p class="text-black">•</p>
      <a class="link link-hover text-black" href="#ressources">Ressources et actualités</a>
      <p class="hidden lg:block text-black">•</p>
    </div>
    <div class="flex gap-4 w-80 items-center justify-center lg:justify-start lg:w-full">
      <a class="link link-hover text-black" href="/#references">Références</a>
      <p class="text-black">•</p>
      <a class="link link-hover text-black" href="#contact">Contact</a>
    </div>
  </div>
  <div>
    <div class="grid grid-flow-col gap-4">
      <a class="text-black"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current"><path d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"></path></svg></a> 
      <a class="text-black"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current"><path d="M19.615 3.184c-3.604-.246-11.631-.245-15.23 0-3.897.266-4.356 2.62-4.385 8.816.029 6.185.484 8.549 4.385 8.816 3.6.245 11.626.246 15.23 0 3.897-.266 4.356-2.62 4.385-8.816-.029-6.185-.484-8.549-4.385-8.816zm-10.615 12.816v-8l8 3.993-8 4.007z"></path></svg></a> 
      <a class="text-black"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current"><path d="M9 8h-3v4h3v12h5v-12h3.642l.358-4h-4v-1.667c0-.955.192-1.333 1.115-1.333h2.885v-5h-3.808c-3.596 0-5.192 1.583-5.192 4.615v3.385z"></path></svg></a>
    </div>
  </div>
  <div>
    <p class="text-black">Copyright © 2022 - All right reserved by adMouvoir</p>
  </div>
</footer>

app/views/partials/_navbar.html.erb
<nav class="navbar bg-gradient-to-r from-bg-primary to-bg-secondary sticky top-0 z-10 p-0">
  <div class="flex-1">
    <div class="w-36 rounded-full">
      <%= link_to root_path do %>
        <p class="pl-4 lg:pl-12 text-xl adm-text-tertiary">
          ad<strong>Mouvoir</strong>
        </p>
      <% end %>
    </div>
  </div>
  <div class="navbar-end">
    <div class="dropdown dropdown-end">
      <label tabindex="0" class="btn-circle">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block w-5 h-5 stroke-current text-white mr-4 rounded"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path></svg>
      </label>
      <ul tabindex="0" class="menu menu-compact dropdown-content adm-bg-secondary w-52 shadow rounded-sm mt-3 p-2">
        <li><%= link_to "Accueil", root_path, class: "text-white" %></li>
        <li><a href="/#a_propos" class="text-white">Qui sommes-nous ?</a></li>
        <li><a href="/#conferences" class="text-white">Conférences-Ateliers</a></li>
        <li><a href="/#experiences" class="text-white">Galerie expériences</a></li>
        <li><a href="/#ressources" class="text-white">Ressources et actualités</a></li>
        <li><a href="/#references" class="text-white">Références</a></li>
        <li><a href="/#contact" class="text-white">Contact</a></li>
        <% if user_signed_in? %>
          <li><%= button_to "Déconnexion", destroy_user_session_path, method: :delete, class: "text-white" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/posts/_form.html.erb
<%= form_with(model: post, class: "contents") do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title, class: "text-2xl font-medium" %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :category, class: "text-2xl font-medium" %>
    <%= form.text_field :category, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <label class="label cursor-pointer justify-start mt-4">
      <%= form.check_box :document, class: "checkbox" %>
      <%= form.label :document, class: "label-text text-2xl ml-4" %>
    </label>
  </div>

  <div class="my-5">
    <%= form.label :content, class: "text-2xl font-medium" %>
    <%= form.text_area :content, rows: 10, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>


  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p class="my-5 text-2xl">
    <%= post.title %>
  </p>

  <p class="my-5 badge badge-lg badge-outline">
    <%= post.category %>
  </p>

  <% if post.document %>
    <p class="my-5">
      Document(s) inclu(s)
    </p>
  <% end %>

  <%= simple_format post.content, class: "my-5 text-xl mb-24" %>

  <% if action_name != "show" %>
    <%= link_to "Voir", post, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Éditer', edit_post_path(post), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/posts/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Éditer Post</h1>

  <%= render "form", post: @post %>

  <%= link_to "Voir", @post, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Retour aux posts", posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/posts/index.html.erb
<div class="w-full px-4 lg:px-20">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 my-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Posts</h1>
    <%= link_to 'Nouveau', new_post_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="posts" class="min-w-full">
    <%= render @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Nouveau post</h1>

  <%= render "form", post: @post %>

  <%= link_to 'Retour aux posts', posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/posts/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 my-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <div class="card card-compact md:card-normal shadow-xl glass mt-12">
      <div class="card-body">
        <%= link_to actualites_path(category: @post.category) do %>
          <p class="text-2xl badge badge-lg badge-outline p-4 my-4"><%= @post.category %></p>
        <% end %>
        <h1 class="card-title adm-text-primary text-2xl lg:text-5xl font-black break-word !mb-8"><%= @post.title %></h1>
        <%= simple_format @post.content, class: "adm-text-tertiary text-2xl break-word" %>
        <% if @post.document %>
          <%=link_to "Télécharger", inscription_path(post_id: @post.id), class: "btn btn-outline text-white mt-6" %>
        <% end %>
      </div>
    </div>
    <%= link_to "Retour vers les ressources et actualités", root_path(anchor: "ressources"), class: "btn btn-outline btn-block text-center text-white mx-auto my-12" %>
    <% if user_signed_in? %>
      <%= link_to 'Éditer', edit_post_path(@post), class: "mt-24 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <div class="inline-block ml-2">
        <%= button_to 'Supprimer', post_path(@post), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
      </div>
      <%= link_to 'Retour aux posts', posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <% end %>
  </div>
</div>

app/views/references/_reference.html.erb
<div id="<%= dom_id reference %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= reference.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">URL:</strong>
    <%= reference.url %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Voir", reference, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Éditer', edit_reference_path(reference), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/references/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Éditer Reference</h1>

  <%= render "form", reference: @reference %>

  <%= link_to "Voir", @reference, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Retour aux références", references_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/references/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">References</h1>
    <%= link_to 'Nouveau', new_reference_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="references" class="min-w-full">
    <%= render @references %>
  </div>
</div>

app/views/references/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Nouvelle reference</h1>

  <%= render "form", reference: @reference %>

  <%= link_to 'Retour aux références', references_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/references/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @reference %>

    <%= link_to 'Éditer', edit_reference_path(@reference), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Supprimer', reference_path(@reference), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Retour aux références', references_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>